AsciiComments:
  # Description: 'Use only ascii symbols in identifiers.'
  Enabled: false

BlockComments:
  # Description: 'Do not use block comments.'
  Enabled: false
  
LineLength:
  # Description: 'Limit lines to 79 characters.'
  Enabled: false
  
DefWithParentheses:
  # Description: 'Use def with parentheses when there are arguments.'
  Enabled: false

DefWithoutParentheses:
  Enabled: false


